### ISSUE TITLE
Make sure all API groups are in their final form

### ISSUE THREAD

**Issue by muvaf** [crossplane-contrib/provider-jet-aws#133]
### What problem are you facing?

With full generation, we automate API group calculations but in some cases we might want to change the ones generated.

### How could Crossplane help solve your problem?

Take a pass over all CRDs (763) and add exceptions as needed in the code so that we don't have to break them later.

**Comment by turkenh** [comment]
@muvaf just in case you're not aware, there is also a resource grouping in the terraform provider repository which could be another input while figuring: https://github.com/hashicorp/terraform-provider-aws/tree/main/internal/service

**Comment by muvaf** [comment]
Thanks! It seems like they recently moved to that folder structure because I remember it was one big folder that contained all of them.
