### ISSUE TITLE
Some APIs at doc.crds.dev are not rendered

### ISSUE THREAD

**Issue by luebken** [crossplane-contrib/provider-jet-aws#134]
### How can we reproduce it?

Some docs render a blank screen at doc.crds.dev. e.g.:
* https://doc.crds.dev/github.com/crossplane-contrib/provider-jet-aws/autoscaling.aws.jet.crossplane.io/AutoscalingGroup/v1alpha1@v0.3.0-preview
* https://doc.crds.dev/github.com/crossplane-contrib/provider-jet-aws/ami.aws.jet.crossplane.io/Copy/v1alpha1@v0.3.0-preview
* https://doc.crds.dev/github.com/crossplane-contrib/provider-jet-aws/ami.aws.jet.crossplane.io/FromInstance/v1alpha1@v0.3.0-preview

Note that these are just random samples.

**Comment by hasheddan** [comment]
@luebken thanks for reporting this! Fix has been implemented and changes are live at https://doc.crds.dev -- let me know if you experience any further issues!

**Comment by luebken** [comment]
Awesome. I've manually tested a few and was able to read all the docs. Thanks.
