### ISSUE TITLE
InternetGateway resource missing in provider-jet-aws@v0.4.2

### ISSUE THREAD

**Issue by andrzej-natzka** [crossplane-contrib/provider-jet-aws#183]
### What resource do you need?
Building EKS cluster requires many resources to be created beforehand: Roles, RolePolicyAttachments, VPCs, SecurityGroup, Subnets, RouteTables, InternetGateway etc. I am building at that moment Compositions for EKS and all resources exist in classic jet provider except **InternetGateway**. This requires to replace [provider-jet-aws@v0.4.2](https://doc.crds.dev/github.com/crossplane-contrib/provider-jet-aws@v0.4.2) with [provider-jet-aws@v0.4.0-preview](https://doc.crds.dev/github.com/crossplane-contrib/provider-jet-aws@v0.4.0-preview). Preview provider comes with almost 800 resources and is very heavy for Kubernetes Cluster comparing with smaller Classic Jet provider. Additionally **InternetGateway** exists in classic crossplane provider so we can treat it as one commonly used managed resources.

### What is your use case?
Being able to build EKS cluster using Classic Jet provider.

**Comment by haarchri** [comment]
with https://github.com/crossplane-contrib/provider-jet-aws/pull/191 back on master so we can have it in the next release

**Comment by andrzej-natzka** [comment]
Tested with jet provider: crossplane/provider-jet-aws:main. All works fine:
`NAME                                                             READY   SYNCED   EXTERNAL-NAME           AGE
internetgateway.ec2.aws.jet.crossplane.io/xpjeteks-hq9fq-fgb4m   True    True     igw-0678f16d8d2205867   11m`

**Comment by andrzej-natzka** [comment]
Thanks for adding IG resource.
